const quoteText = document.querySelector(".quote"),
quoteBtn = document.querySelector("button"),
authorName = document.querySelector(".name"),
speechBtn = document.querySelector(".speech"),
copyBtn = document.querySelector(".copy"),
twitterBtn = document.querySelector(".twitter"),
synth = speechSynthesis;

function automaticButtonClick() {
  document.getElementById("temaBotao").click();
}

function randomQuote(){
	const temas = [
	"A influência da tecnologia na comunicação interpessoal.",
	"O impacto das redes sociais na saúde mental dos jovens.",
	"A privacidade e a segurança na era digital.",
	"A regulação da internet e o papel do Estado.",
	"As fake news e a desinformação na era digital.",
	"O uso da tecnologia para aprimorar a educação.",
	"O papel das redes sociais na democracia.",
	"O impacto da tecnologia na economia.",
	"O uso de inteligência artificial na vida cotidiana.",
	"A acessibilidade digital e a inclusão social.",
	"A responsabilidade civil dos usuários na internet.",
	"Os direitos autorais e a pirataria na era digital.",
	"O uso da tecnologia na saúde.",
	"A função das redes sociais na política.",
	"O papel da tecnologia no desenvolvimento sustentável.",
	"Os desafios da segurança digital.",
	"O impacto da tecnologia na cultura e nas artes.",
	"A influência das redes sociais na formação da opinião pública.",
	"O uso da tecnologia para aprimorar a segurança pública.",
	"O consumo excessivo de conteúdo virtual",
	"A ética na tecnologia e na internet.",
	"A responsabilidade das empresas de tecnologia na proteção dos dados dos usuários.",
	"A transformação digital na agricultura e a produção de alimentos do futuro.",
	"O papel da tecnologia na mobilidade urbana.",
	"A regulação da inteligência artificial.",
	"A privacidade na era dos dispositivos inteligentes.",
	"O impacto das redes sociais na comunicação política.",
	"A censura na internet e a liberdade de expressão.",
	"O papel da tecnologia na prevenção de desastres naturais.",
	"A influência das redes sociais na autoestima.",
	"A inclusão digital e a desigualdade social.",
	"Os desafios da segurança cibernética para as empresas.",
	"O papel da tecnologia na justiça.",
	"A cultura do cancelamento.",
	"O uso da tecnologia na geração de empregos.",
	"A privacidade e a segurança nas redes sociais.",
	"A relação entre a tecnologia e a violência.",
	"As barreiras da regulação do comércio virtual.",
	"O papel da tecnologia na preservação do meio ambiente.",
	"A influência das redes sociais na autoimagem.",
	"A acessibilidade das pessoas com deficiência na era digital.",
	"O impacto das redes sociais na publicidade.",
	"O uso da tecnologia na prevenção de doenças.",
	"A regulação da inteligência artificial na área médica.",
	"A privacidade e a segurança nos dispositivos inteligentes.",
	"O impacto das redes sociais na educação.",
	"O papel da tecnologia na segurança alimentar.",
	"A ética na coleta e no uso de dados na internet.",
	"A relação entre tecnologia e direitos humanos.",
	"Os obstáculos da inclusão social relativos a baixa qualidade da educação e formação à distância.",
	"Prevenção de crimes cibernéticos e a proteção dos direitos humanos na internet.",
	"Os limites da liberdade de expressão na internet.",
	"As consequências do uso indevido de dados pessoais.",
	"A cidadania digital e a importância do engajamento cívico nas redes sociais.",
	"A segurança digital nas eleições.",
	"A regulamentação do uso de conteúdo digital.",
	"O cyberbullying e a importância da educação digital na prevenção e combate ao assédio virtual.",
	"A inclusão digital e o acesso à internet como direito humano fundamental.",
	"O papel da telemedicina na democratização do acesso à saúde e na melhoria da qualidade de vida da população.",
	"A ética e a segurança na coleta e uso de dados de saúde em tecnologias de monitoramento e tratamento.",
	"O uso de inteligência artificial na identificação de doenças e na prevenção de epidemias.",
	"O uso de tecnologias assistivas para a inclusão de pessoas com deficiência na saúde.",
	"A influência da educação digital na prevenção de doenças e no autocuidado da saúde.",
	"A função da teleconsulta e a telemedicina como alternativas ao atendimento presencial.",
	"O papel das redes sociais e dos aplicativos de saúde na promoção da saúde mental e no combate à estigmatização de doenças psicológicas.",
	"O impacto da tecnologia na democratização do acesso à cultura e nas mudanças de hábitos culturais da sociedade.",
	"A preservação e difusão do patrimônio cultural por meio de tecnologias digitais.",
	"O papel da tecnologia na promoção da diversidade cultural e na valorização da arte regional.",
	"A segurança e a privacidade na distribuição de conteúdo cultural por meio de plataformas online.",
	"A criação de novas linguagens artísticas a partir do uso de tecnologias digitais.",
	"O papel das redes sociais na promoção e difusão de manifestações culturais e artísticas.",
	"A importância da educação digital na formação de público para a cultura e nas artes.",
	"O impacto da tecnologia no mercado cultural e nas mudanças nas relações de trabalho dos artistas.",
	"As potencialidades e os riscos da substituição de experiências culturais presenciais por meio de tecnologias digitais.",
	"A implementação de câmeras de segurança e tecnologias de vigilância em espaços públicos.",
	"Os limites éticos e legais do uso de IA e big data para prevenir e combater crimes.",
	"O uso de tecnologias de reconhecimento facial na segurança pública.",
	"O uso de drones em operações de segurança pública.",
	"A influência do treinamento das forças de segurança em tecnologias de segurança para garantir o uso adequado das ferramentas disponíveis.",
	"O uso de tecnologias de realidade virtual para treinamento e simulação de situações de risco para os policiais.",
	"O impacto da tecnologia na redução da violência policial e na proteção dos direitos humanos.",
	"A utilização de sistemas eletrônicos de votação: benefícios e riscos.",
	"A utilização de sistemas analógicos de votação: benefícios e riscos.",
	"Os desafios éticos e legais na utilização de inteligência artificial na análise de dados e tomada de decisão política.",
	"O impacto da tecnologia no combate à corrupção.",
	"A utilização de tecnologias para aprimorar a transparência e eficiência do poder judiciário na resolução de conflitos.",
	"O combate à pornografia infantil.",
	"A importância da educação digital para a formação de crianças e adolescentes no uso adequado e seguro da tecnologia.",
	"A educação familiar na era digital.",
	"A inclusão e acessibilidade de crianças e adolescentes com deficiência ou necessidades especiais no cenário digital.",
	"A exposição infantil a conteúdos impróprios e predadores virtuais no ambiente digital.",
	"A influência da tecnologia na socialização e formação de identidade de crianças e adolescentes.",
	"O fomento ao desenvolvimento cognitivo e habilidades socioemocionais de crianças e adolescentes na internet.",
	"A promoção da diversidade e representatividade na cultura e mídia consumidas pelos jovens na internet.",
	"A automação e o futuro do trabalho.",
	"Trabalho remoto: impactos na saúde mental e produtividade.",
	"Reflexos e implicações da nova forma de trabalho através de aplicativos de serviços.",
	"O uso de inteligência artificial no recrutamento e seleção de candidatos.",
	"O direito à desconexão: como a tecnologia mudou a forma como trabalhamos e a importância de estabelecer limites.",
	"Os desafios e oportunidades para os trabalhadores diante do acelerado avanço tecnológico.",
	"Os desafios da universalização da educação para a inserção no trabalho.",
	"Os dilemas entre a precarização do trabalho e a manutenção dos direitos do trabalhador.",
	"As desigualdades de gênero no ambiente de trabalho.",
	"Os impasses para a inclusão de pessoas com deficiência no cenário atual de trabalho.",
	"Os impactos do trabalho infantil na sociedade.",
	"A influência da segurança civil no ambiente de trabalho.",
	"Os desafios da terceirização do trabalho.",
	"O papel da formação profissional na empregabilidade.",
	"As perpectivas e os dilemas do trabalho informal na atualidade.",
	"O papel do empreendedorismo na geração de empregos.",
	"Os desafios da conciliação entre trabalho e vida pessoal.",
	"A importância da valorização do trabalho doméstico.",
	"A relação entre trabalho e saúde mental.",
	"O impacto da globalização no mercado de trabalho.",
	"A importância do trabalho voluntário para a sociedade.",
	"Os impasses da diversidade cultural no ambiente de trabalho.",
	"A relação entre trabalho e aposentadoria.",
	"O papel das políticas públicas na geração de empregos.",
	"A relação entre trabalho e meio ambiente.",
	"Os desafios da inclusão social no mercado de trabalho de profissionais da saúde.",
	"A importância da qualificação profissional para a empregabilidade.",
	"O papel das empresas na promoção da igualdade de oportunidades no trabalho.",
	"A relação entre trabalho e renda.",
	"Os desafios da rotatividade no mercado de trabalho.",
	"A importância da segurança financeira no ambiente de trabalho.",
	"A relação entre trabalho e empreendedorismo.",
	"Os desafios da saúde e segurança no trabalho.",
	"A importância da liderança no ambiente de trabalho.",
	"Os desafios da concorrência no mercado de trabalho.",
	"A importância da diversidade de habilidades no ambiente de trabalho.",
	"O papel da inovação na geração de empregos.",
	"A relação entre trabalho e mobilidade social.",
	"Os desafios da jornada de trabalho e a flexibilidade.",
	"A influência do trabalho cooperativo para o desenvolvimento social.",
	"Os impactos da crise econômica no mercado de trabalho.",
	"A relação entre trabalho e responsabilidade social.",
	"Os desafios da segurança no trabalho remoto.",
	"A construção de estruturas éticas no ambiente de trabalho.",
	"O papel das políticas de inclusão para minorias no mercado de trabalho.",
	"Os desafios da formação profissional continuada.",
	"A importância da valorização do trabalho artesanal.",
	"Os impactos da automação no mercado de trabalho.",
	"A relação entre trabalho e inovação tecnológica.",
	"Discussões sobre a jornada de trabalho e a sua redução no modelo atual para um número inferior a 40 horas.",
	"O impacto da terceirização na precarização do trabalho no Brasil.",
	"A importância da regulamentação da terceirização para a proteção dos trabalhadores.",
	"Como a informalidade afeta a produtividade no mercado de trabalho?",
	"Os desafios da formalização do trabalho no Brasil.",
	"O papel da tecnologia na redução da informalidade no mercado de trabalho.",
	"Terceirização: vantagens e desvantagens para empresas e trabalhadores.",
	"O papel do Estado na garantia dos direitos dos trabalhadores terceirizados.",
	"A relação entre a informalidade e a falta de acesso a benefícios trabalhistas.",
	"A importância da fiscalização do trabalho para combater a informalidade.",
	"Os riscos da terceirização para a saúde e segurança dos trabalhadores.",
	"A informalidade como entrave para a obtenção de crédito e financiamento.",
	"Os impactos econômicos da informalidade no mercado de trabalho.",
	"A relação entre a produtividade e a qualidade de vida no trabalho.",
	"Como a formalização do trabalho pode contribuir para o crescimento econômico?",
	"A terceirização e a desigualdade salarial no Brasil.",
	"A precarização do trabalho e seus efeitos na vida social e familiar dos trabalhadores.",
	"A relação entre a informalidade e a falta de proteção social.",
	"A terceirização como forma de reduzir custos empresariais.",
	"A informalidade como resultado da falta de políticas públicas para o mercado de trabalho.",
	"Os desafios do trabalho voluntário durante situações de pandemia e desastres naturais",
	"Trabalho na velhice: os dilemas de se manter ativo após a aposentadoria",
	"Os impactos da reforma da previdência na vida dos trabalhadores brasileiros",
	"O papel das empresas na luta contra o trabalho escravo contemporâneo",
	"A importância da fiscalização do trabalho infantil para a proteção das crianças e adolescentes",
	"Trabalho infantil: os desafios na erradicação dessa prática no Brasil",
	"O impacto do trabalho escravo na economia brasileira e no desenvolvimento social",
	"Como estimular a produtividade do trabalho sem prejudicar a qualidade de vida dos trabalhadores?",
	"A relevância do salário mínimo para a garantia de uma vida digna para os trabalhadores.",
	"O papel do sindicalismo na defesa dos direitos dos trabalhadores: desafios e perspectivas.",
	"O enfrentamento à desigualdade regional de oportunidades no mercado de trabalho brasileiro.",
	"A atuação do MTST e a luta por moradia e o direito ao trabalho.",
	"O papel das empresas digitais na economia global e no trabalho.",
	"A atuação de empresas multinacionais em países em desenvolvimento.",
	"A influência das grandes corporações no processo político e nas decisões governamentais.",
	"A exploração de recursos naturais por empresas multinacionais e seus impactos sociais, culturais e ambientais.",
	"As políticas de responsabilidade social corporativa adotadas por empresas e sua efetividade.",
	"A concentração de poder econômico corporativo e seus efeitos na democracia.",
	"A relação entre as empresas digitais e o monopólio da informação e do conhecimento.",
	"A relevância da valorização dos servidores públicos para a qualidade do serviço prestado à população.",
	"A necessidade de modernização e digitalização dos serviços públicos para aumentar a eficiência e a transparência.",
	"A responsabilidade dos gestores públicos na garantia do acesso igualitário da população aos serviços públicos.",
	"Os desafios do serviço público na garantia dos direitos das minorias e grupos vulneráveis.",
	"A importância do controle social no acompanhamento e fiscalização do serviço público.",
	"A ética no serviço público e a importância da integridade dos servidores na prevenção da corrupção.",
	"A educação e capacitação contínua dos servidores públicos para a melhoria do serviço prestado à população.",
	"A relação entre o serviço público e o desenvolvimento econômico e social do país.",
	"A garantia dos direitos sociais previstos na Constituição.",
	"A criminalização do mercado ambulante e camelô: reflexões sobre a informalidade e a segurança pública.",
	"O trabalho sexual e a criminalização: discutindo a proteção e a segurança das trabalhadoras.",
	"A estigmatização do trabalho artístico de rua.",
	"O impacto do tráfico de drogas no mercado de trabalho informal.",
	"A relação entre a legalização das drogas e a redução do tráfico e violência.",
	"Os dilemas do impacto do tráfico de drogas na economia e no desenvolvimento social.",
	"A relação entre a criminalização do uso de drogas e a marginalização do trabalhador.",
	"A relação entre o tráfico de drogas e o trabalho infantil e escravo.",
	"Os desafios da reinserção no mercado de trabalho de pessoas em recuperação de dependência química.",
	"Reciclagem: estamos levando à serio ou tornou-se um mito?",
	"Desmatamento na Amazônia: uma ameaça à biodiversidade.",
	"O papel da agricultura sustentável na preservação do meio ambiente.",
	"Os impactos do aquecimento global no planeta.",
	"Poluição do ar: causas, consequências e soluções.",
	"O uso excessivo de plásticos e seus efeitos no meio ambiente.",
	"Energias renováveis como alternativa aos combustíveis fósseis.",
	"A importância da preservação dos oceanos para o equilíbrio do planeta.",
	"Desafios da gestão de resíduos sólidos nas grandes cidades.",
	"O papel da sociedade na preservação do meio ambiente.",
	"Os efeitos do consumo excessivo no meio ambiente.",
	"A conexão entre desenvolvimento econômico e preservação do meio ambiente.",
	"O impacto da exploração mineral na natureza.",
	"A necessidade de políticas públicas para a preservação do meio ambiente.",
	"Agricultura e desmatamento: desafios e soluções.",
	"A importância da arborização urbana para a qualidade de vida dos habitantes.",
	"As consequências da poluição dos rios para a saúde e o meio ambiente.",
	"A questão do lixo eletrônico: descarte adequado e reciclagem.",
	"A crise hídrica e a gestão dos recursos hídricos.",
	"A influência das mudanças climáticas na economia mundial.",
	"O papel da educação na formação de uma consciência ambiental.",
	"A conexão entre a urbanização e os problemas ambientais.",
	"O papel das empresas na preservação do meio ambiente.",
	"O impacto da pecuária no meio ambiente.",
	"A necessidade de redução da emissão de gases de efeito estufa.",
	"A preservação da fauna e flora brasileira.",
	"O uso de agrotóxicos na agricultura e seus efeitos no meio ambiente e na saúde.",
	"Os desafios da gestão ambiental nas indústrias.",
	"A importância da preservação das florestas para a biodiversidade.",
	"As consequências do descarte inadequado de resíduos químicos.",
	"O papel das energias renováveis na redução da emissão de poluentes.",
	"A conexão entre a urbanização e a falta de áreas verdes.",
	"A poluição sonora e seus efeitos na saúde e no meio ambiente.",
	"A gestão ambiental nas áreas urbanas.",
	"A importância da preservação das águas subterrâneas.",
	"A questão do desperdício de alimentos e seu impacto no meio ambiente.",
	"A conexão entre o turismo e os impactos ambientais.",
	"A conscientização sobre o consumo sustentável.",
	"A gestão de áreas ambientais protegidas e a responsabilidade civil.",
	"A importância da preservação dos recursos naturais para as gerações futuras.",
	"A conexão entre a exploração de recursos naturais e os conflitos sociais.",
	"A poluição visual e seus efeitos na qualidade de vida urbana.",
	"A gestão ambiental nas áreas rurais: perspectivas e problemáticas.",
	"A nova ordem geopolítica global e o papel das superpotências emergentes.",
	"O futuro das relações humanas: impactos das redes sociais e da inteligência artificial.",
	"Os conflitos éticos e jurídicos da biotecnologia no futuro da humanidade.",
	"O futuro do transporte aéreo: aviões elétricos, hipersônicos e drones.",
	"A revolução da indústria 4.0: a automação e a internet das coisas.",
	"As implicações éticas e sociais da tecnologia de edição genética.",
	"O futuro da mobilidade urbana: veículos elétricos, autônomos e compartilhados.",
	"A falta de políticas públicas adequadas para lidar com desastres naturais em áreas de vulnerabilidade social.",
	"As consequências econômicas dos desastres naturais.",
	"A conexão entre mudanças climáticas e o aumento da frequência e intensidade de desastres naturais.",
	"A importância da solidariedade e ajuda humanitária em situações de desastres e conflito urbano.",
	"O impacto dos desastres naturais na saúde mental das pessoas afetadas.",
	"O papel da mídia na divulgação de informações precisas e úteis em situações de desastres.",
	"As consequências políticas da má resposta aos prevenção e controle de desastres naturais.",
	"A conexão entre desastres naturais e imigração forçada.",
	"Os efeitos socioeconômicos de desastres ambientais em áreas rurais.",
	"O papel das ONGs na prevenção e resposta a desastres.",
	"As consequências dos desastres naturais na segurança alimentar.",
	"A conexão entre a urbanização desenfreada e o aumento da vulnerabilidade a desastres naturais e humanos.",
	"A violência urbana e a segurança pública nas grandes cidades.",
	"Os impactos dos conflitos urbanos na economia.",
	"Os desafios do planejamento urbano para lidar com conflitos entre diferentes grupos sociais.",
	"Os direitos humanos e as ações policiais em conflitos urbanos.",
	"A importância da mediação de conflitos na prevenção de violência urbana.",
	"Os conflitos urbanos e a exclusão social: como garantir o acesso a serviços públicos e oportunidades para todos.",
	"Os impactos das remoções forçadas de comunidades em conflitos urbanos.",
	"O papel da imprensa na cobertura de conflitos urbanos e sua influência na opinião pública.",
	"A conexão entre a criminalidade e os conflitos urbanos: como a ação do crime organizado afeta a dinâmica social nas cidades.",
	"Os conflitos urbanos e a preservação do patrimônio cultural e histórico das cidades.",
	"Os desafios da gestão pública para solucionar conflitos urbanos de forma efetiva e justa.",
	"As soluções alternativas de resolução de conflitos em comunidades urbanas.",
	"A participação da sociedade civil na prevenção e resolução de conflitos urbanos.",
	"Os conflitos entre moradores e empresas em áreas urbanas: como equilibrar interesses diferentes.",
	"Os conflitos urbanos e o direito à moradia: como garantir o acesso à habitação digna para todos.",
	"As relações de poder e as dinâmicas de conflito em áreas periféricas das cidades.",
	"Turismo e urbanismo: como planejar cidades atraentes sem eliminar sua identidade.",
	"O impacto econômico de acidentes de trânsito e formas de reduzir esses custos.",
	"Os desafios enfrentados pelos serviços de emergência para lidar com grandes desastres naturais.",
	"A necessidade de regulamentação mais rigorosa para prevenir acidentes envolvendo produtos químicos.",
	"Os impactos psicológicos em sobreviventes de acidentes graves e suas famílias.",
	"O dilema do fomento à prática de esportes e os riscos de atividades esportivas radicais.",
	"A necessidade de investimentos em infraestrutura para reduzir a frequência de acidentes em estradas e pontes.",
	"A importância da rápida resposta em situações de emergência para minimizar danos e salvar vidas.",
	"Os custos sociais e econômicos do desastre de Mariana e a necessidade de medidas preventivas em relação à mineração.",
	"Os desafios enfrentados pelos profissionais de saúde em emergências e situações de acidentes graves.",
	"O papel dos governos e das organizações internacionais em ajudar as vítimas de desastres humanitários.",
	"O impacto econômico e ambiental dos acidentes de petróleo em áreas costeiras.",
	"Os cuidados necessários para evitar incêndios em áreas urbanas e estabelecimentos públicos e privados.",
	"As políticas governamentais para garantir a segurança em eventos esportivos e culturais.",
	"As consequências da verticalização das cidades para a qualidade de vida dos habitantes.",
	"Como a gentrificação afeta a diversidade cultural nas áreas urbanas?",
	"A importância da preservação do patrimônio histórico nas áreas urbanas.",
	"Os desafios da regularização fundiária nas áreas urbanas.",
	"O papel dos espaços públicos na promoção da convivência e do bem-estar nas cidades.",
	"Como a especulação imobiliária impacta a oferta de moradias acessíveis nas áreas urbanas?",
	"A conexão entre urbanismo e saneamento básico: como garantir o acesso à água e ao esgoto nas cidades?",
	"Os desafios do planejamento urbano em cidades em desenvolvimento acelerado.",
	"O papel da filosofia e da sociologia na sociedade atual e na formação do indivíduo crítico.",
	"A relação entre indivíduo e sociedade na teoria sociológica clássica.",
	"O conceito de liberdade na filosofia política moderna.",
	"A influência da tecnologia na nossa compreensão do tempo e do espaço.",
	"A conexão entre ética e política na filosofia contemporânea.",
	"O papel da arte na construção de identidades sociais.",
	"O função do trabalho na construção de identidades sociais.",
	"Os laços entre religião, sociedade e política nas relações sociais.",
	"A construção social do gênero e da sexualidade.",
	"O conceito de poder na teoria sociológica crítica.",
	"A influência da mídia na formação de opinião pública sobre ocorrências policiais.",
	"A relação entre indivíduo e natureza na filosofia ambiental.",
	"A relação entre indivíduo e Estado na filosofia política clássica.",
	"O papel da cultura na formação das identidades coletivas.",
	"A relação entre indivíduo e sociedade na teoria sociológica contemporânea.",
	"O papel da educação na formação de valores e atitudes sociais com um olhar para os moradores de rua.",
	"A influência da globalização na cultura e na identidade social dos países de terceiro mundo.",
	"A conexão entre ação coletiva e transformação social.",
	"O indivíduo e a coletividade na filosofia política contemporânea.",
	"O conceito de justiça na filosofia política.",
	"O papel da violência na construção e desconstrução de identidades sociais.",
	"A função da arte na crítica social e suas ramificações.",
	"O papel da história na formação da consciência coletiva.",
	"As ramificações do conceito de alienação na teoria sociológica.",
	"O papel da religião na construção de valores sociais.",
	"O papel da linguagem na construção de significados sociais com o advento da internet.",
	"A função do consumo na construção de identidades sociais e suas alternativas.",
	"O conceito de ideologia na teoria sociológica crítica.",
	"O dever da ciência e da filosofia na formação de valores e atitudes sociais.",
	"A cultura como motor na construção da memória e vivências coletivas de uma nação.",
	"A influência do capitalismo na forma como lidamos com a morte e os rituais funerários.",
	"O Estado e a sociedade no debate sobre o direito à morte.",
	"Discussões sobre o luto na era das redes sociais e os impactos da mídia sobre a forma de como lidamos com a morte.",
	"A relevância da função da arte na nossa compreensão da morte.",
	"De que maneiras e até que ponto o patrocínio cultural por empresas privadas influência as produções artísticas?",
	"A censura na arte e suas consequências para a liberdade de expressão.",
	"A representatividade na cultura e seu impacto na diversidade cultural.",
	"As vivências do 'homem branco': como comunidades isoladas são afetadas pela influência cultural de comunidades urbanas na atualidade?",
	"A preservação do patrimônio cultural e histórico do brasil e o seu possível apagamento.",
	"A função social do entretenimento e seu impacto na saúde mental da população.",
	"O racismo estrutural e a necessidade de desconstrução a beleza negra.",
	"Os reflexos do etarismo na sociedade brasileira.",
	"A legalização do aborto no mundo: perspectivas, resultados e implementação.",
	"A representatividade feminina na política brasileira.",
	"Um panorama do feminismo transexcludente.",
	"A quebra de tabus em relação ao uso medicinal da maconha no Brasil.",
	"Uma discussão sobre violência doméstica cometida contra homens.",
	"O uso de métodos anticoncepcionais masculinos no Brasil.",
	"A descriminalização da prostituição no Brasil os tabus persistentes sobre a sexualidade feminina.",
	"O feminismo interseccional na luta contra a discriminação de minorias.",
	"O uso da imagem feminina na publicidade e na mídia moderna.",
	"A evolução das plataformas digitais de conteúdo adulto.",
	"A atribuição das plataformas como de conteúdo adulto na economia da sexualidade.",
	"A relação entre as plataformas de conteúdo adulto e a cultura do cancelamento na internet.",
	"O impacto das plataformas de conteúdo adulto na saúde mental dos usuários e dos trabalhadores do setor.",
	"O papel das plataformas de conteúdo adulto na construção da imagem e do papel da mulher na sociedade.",
	"O uso de plataformas de conteúdo adulto e o aumento da violência sexual contra mulheres e crianças.",
	"A atribuição e o papel da figura masculina na gravidez e no pós-parto em casais heteronormativos.",
	"A violência obstétrica e suas consequências para a saúde física e mental da mulher",
	"O papel da vacinação na erradicação de doenças e os obstáculos à adesão universal.",
	"Os riscos da cesárea desnecessária e a importância do parto natural.",
	"O papel da alimentação na prevenção de doenças.",
	"Os desafios da saúde pública em meio à pandemia.",
	"Os perigos da automedicação e a prevalência da venda de remédios sem receita médica.",
	"O mercado paralelo de esteróides anabolizantes.",
	"A influência da publicidade na escolha de produtos de saúde e as ramificações econômicas dessa influência.",
	"O advento dos medicamentos genéricos e a sua importância para o mercado farmacêutico no Brasil.",
	"Os desafios da saúde pública no combate à obesidade.",
	"Os riscos e cuidados necessários em uma gravidez na adolescência.",
	"O impacto das doenças crônicas na qualidade de vida.",
	"A persistência dos desafios da saúde pública no combate ao HIV/AIDS.",
	"Os desafios da saúde pública na prevenção de epidemias em áreas isoladas.",
	"Um panorama sobre o tratamento e a prevenção do câncer de mama no Brasil.",
	"A inclusão de pessoas gestantes trans e não binárias na assistência à gravidez.",
	"Os efeitos destrutivos do tabagismo.",
	"Uma discussão sobre a homeopatia na cultura da saúde brasileira.",
	"Um panorama sobre a abordargem da prevenção de doenças sexualmente transmissíveis para os jovens.",
	"Os desafios da saúde pública no combate à desnutrição infantil.",
	"A medicalização excessiva do parto e suas consequências para a saúde da mãe e do bebê.",
	"A privação do sono e os seus efeitos na saúde e no trabalho.",
	"O autodiagnóstico de condições como autimo e TDAH e como essa atitude impacta a vida do indivíduo.",
	"O mercado ilegal de medicamentos tarja preta.",
	"Deus proverá: como a religião pode influenciar a escolha de tratamentos médicos?",
	"O panorama do combate à tuberculose na atualidade e suas perspectivas.",
	"O papel da fisioterapia na prevenção e tratamento de doenças.",
	"O consumo de água e a importância da prevenção de doenças renais.",
	"O impacto da falta de acesso à água potável na saúde.",
	"A garantia de acesso à saúde de qualidade para crianças com condições médicas crônicas.",
	"O papel da sociedade na prevenção do suicídio.",
	"A estigmatização de pessoas com condições mentais na mídia.",
	"A relação entre condições socioeconômicas e transtornos mentais na população brasileira.",
	"O aumento da prevalência de condições psicológicas durante a pandemia da COVID-19.",
	"Como a falta de informação sobre a sexualidade de pessoas idosas e com deficiência contribui para a discriminação e o preconceito?",
	"Como a sociedade se opõe à garantia de direito à sexualidade para pessoas idosas e com deficiência?",
	"Os estereótipos de gênero e idade que afetam a expressão da sexualidade de pessoas idosas e com deficiência.",
	"A questão da autonomia sexual de pessoas idosas e com deficiência e os direitos sexuais como direitos humanos fundamentais.",
	"Uma discussão sobre a falta de atividade sexual e o aumento do risco de depressão e outras condições mentais em pessoas idosas e com deficiência.",
	"O papel da família e dos cuidadores na promoção da sexualidade de pessoas idosas e com deficiência.",
	"As consequências socioeconômicas de uma gravidez não planejada.",
	"O direito à licença-maternidade e suas implicações para a igualdade de gênero.",
	"A influencia dos povo indígenas para a formação histórica da america latina e do Brasil.",
	"Quem construiu o Brasil? uma discussão sobre o papel dos africanos e indígernas na construção do Brasil.",
	"Os efeitos do processo de colonização portuguesa no Brasil e possíveis impactos na atualidade.",
	"Um panorama do período colonial brasileiro e sua influência na protoeconomia do país.",
	"Uma abordagem sobre os items de arte e peças roubadas por processos históricos e seu reestabelecimento no país de origem.",
	"Os ideais de liberdade do Brasil motivados por lutas sociais históricas como a Inconfidência Mineira.",
	"A escravidão no Brasil e sua influência na formação social, política e econômica do país.",
	"A Proclamação da República e o fim do Império.",
	"A Revolta da Chibata e a luta pelos direitos dos marinheiros.",
	"A participação do Brasil na Primeira Guerra Mundial.",
	"A Revolução de 1930 e o início do governo de Getúlio Vargas.",
	"A Era Vargas e as mudanças políticas e sociais no Brasil.",
	"A participação do Brasil na Segunda Guerra Mundial.",
	"A construção de Brasília e a modernização do país.",
	"A Ditadura Militar no Brasil e suas consequências na sociedade.",
	"A luta pelos direitos civis e sociais durante a Ditadura Militar.",
	"A redemocratização do Brasil e o fim da Ditadura Militar.",
	"O processo de impeachment: o que ele representa e quais suas ramificações na história do brasil.",
	"A Lei Áurea e a abolição da escravatura no Brasil.",
	"A Revolta da Vacina e a importância da saúde pública no país.",
	"A Revolução Constitucionalista de 1932 e os ideais de democracia.",
	"O papel dos movimentos sociais na luta pela democracia no Brasil.",
	"A política externa brasileira durante o governo de Getúlio Vargas.",
	"A luta pelos direitos dos trabalhadores e a criação da CLT.",
	"A Guerra do Paraguai e sua influência na formação do Estado brasileiro.",
	"A relação entre a Igreja Católica e o Estado brasileiro ao longo da história.",
	"A participação do Brasil na criação da ONU.",
	"A construção da Rodovia Transamazônica e a integração nacional.",
	"A fundação da Petrobras e a exploração do petróleo no Brasil.",
	"A luta dos povos indígenas pelos seus direitos no Brasil.",
	"A literatura brasileira e sua importância na formação cultural do país.",
	"O movimento modernista e a renovação artística e literária no Brasil.",
	"A construção das hidrelétricas no Brasil e sua importância para a economia.",
	"A participação do Brasil na criação dos BRICS.",
	"A história do futebol no Brasil e sua influência na cultura nacional.",
	"A música brasileira e sua importância na formação da identidade cultural.",
	"A Revolta dos Muckers e a luta pela liberdade religiosa.",
	"A luta dos quilombolas pelo reconhecimento de seus direitos.",
	"A história do Carnaval no Brasil e sua importância na cultura popular.",
	"A arquitetura colonial brasileira e sua influência na cultura nacional.",
	"A importância do comércio internacional para o desenvolvimento econômico do Brasil.",
	"A relação entre a economia brasileira e a crise econômica mundial.",
	"Os desafios da inserção do Brasil no mercado internacional.",
	"O papel do Brasil nas relações econômicas com os países da América Latina.",
	"Os impactos da guerra comercial entre Estados Unidos e China na economia brasileira.",
	"A importância dos acordos comerciais para o Brasil.",
	"A questão da dívida externa brasileira e suas consequências.",
	"A relação entre as políticas econômicas adotadas pelo Brasil e as políticas econômicas internacionais.",
	"O papel das empresas estrangeiras no desenvolvimento econômico do Brasil.",
	"Os desafios da internacionalização das empresas brasileiras.",
	"A relação entre o câmbio e a economia brasileira.",
	"As políticas cambiais adotadas pelo Brasil e suas consequências.",
	"A importância do investimento estrangeiro direto para a economia brasileira.",
	"A questão da desindustrialização e suas implicações para a economia brasileira.",
	"As políticas econômicas adotadas pelos países desenvolvidos e suas consequências para o Brasil.",
	"A importância do mercado interno para a economia brasileira.",
	"Os impactos da crise política na economia brasileira.",
	"Os desafios da política econômica para o desenvolvimento do Nordeste brasileiro.",
	"O papel do Poder Judiciário na garantia da justiça social no Brasil.",
	"A necessidade de uma reforma do sistema penitenciário brasileiro para garantir uma justiça mais efetiva.",
	"A aplicação do direito à luz da justiça restaurativa.",
	"Justiça e igualdade: como garantir que a lei seja aplicada de forma justa para todos os cidadãos?",
	"A atribuição da mídia na construção da imagem de culpados e inocentes: até que ponto isso afeta a justiça?",
	"A necessidade de combater a corrupção no sistema judiciário para garantir uma justiça efetiva.",
	"A criminalização de condutas sociais como forma de garantir a justiça ou como forma de opressão social?",
	"A importância da mediação de conflitos como forma de garantir a justiça e evitar a judicialização excessiva.",
	"A influência das redes sociais na justiça: como as informações compartilhadas podem influenciar o julgamento de um processo?",
	"A justiça e a questão da violência policial no Brasil: como garantir que os policiais cumpram a lei e não abusem de seu poder?",
	"A questão da prisão preventiva: como garantir que ela seja aplicada de forma justa e proporcional?",
	"A atribuição do Ministério Público na garantia da justiça no Brasil.",
	"A importância da transparência no sistema judiciário para garantir uma justiça mais efetiva.",
	"Justiça e direitos humanos: como garantir que os direitos humanos sejam respeitados no sistema judiciário?",
	"A problemática dos refugiados climáticos.",
	"A gestão dos recursos pesqueiros e a pesca predatória.",
	"A questão da desertificação e a degradação ambiental em regiões áridas.",
	"A produção de energia eólica e a geografia do vento no Brasil.",
	"A crise humanitária dos refugiados no mundo.",
	"A manutenção dos ideais da liberdade de imprensa para a democracia.",
	"Os desafios para o combate à violência doméstica no Brasil.",
	"A crise política e humanitária na Venezuela.",
	"A panorama sobre a pobreza e a fome no mundo.",
	"A crise migratória e os desafios para a integração dos imigrantes na Europa.",
	"Os desafios para a preservação das línguas indígenas no Brasil.",
	"A crise política e humanitária na Síria.",
	"O conflito Rússia e Ucrânia.",
	"Os desafios para o combate à obesidade no Brasil.",
	"A crise política e humanitária no Afeganistão.",
	"Os desafios para a preservação da diversidade étnica e cultural na África.",
	"A efetividade das políticas públicas de prevenção e combate ao crime no Brasil.",
	"A superlotação do sistema prisional brasileiro e suas consequências sociais e econômicas.",
	"A influência do sistema carcerário na reincidência criminal no Brasil.",
	"A criminalização do aborto no Brasil e seus impactos na saúde das mulheres.",
	"A criminalidade no campo: os conflitos agrários e a violência no campo brasileiro.",
	"A legalização das drogas como estratégia de combate à violência e ao tráfico de drogas.",
	"A influência do tráfico de drogas na violência urbana brasileira.",
	"A eficácia da Lei Maria da Penha na proteção das mulheres vítimas de violência doméstica.",
	"A criminalização da homofobia e seus impactos na proteção dos direitos da população LGBTQIA+.",
	"O sistema de justiça criminal no Brasil: desafios e possíveis soluções.",
	"A redução da maioridade penal como medida de combate ao crime: argumentos a favor e contra.",
	"A criminalização da posse e do porte de armas no Brasil e seus impactos na segurança pública.",
	"O voto consciente para o fortalecimento da democracia.",
	"A polarização política como obstáculo ao diálogo democrático.",
	"A influência do financiamento público de campanhas eleitorais.",
	"A influência do financiamento privado de campanhas eleitorais.",
	"A função da imprensa na divulgação da informação política e suas ramificações.",
	"Discussões sobre a regulamentação da imprensa.",
	"Os desafios da participação política da população LGBTQ+.",
	"A influência do poder econômico das diferentes classes sociais nas eleições e na política em geral.",
	"A participação dos jovens na política brasileira e nas eleições.",
	"A educação política nas escolas e a participação dos professores na formação política dos alunos.",
	"Os desafios da participação política dos povos indígenas no Brasil.",
	"A política de cotas como forma de inclusão social.",
	"A participação política e social dos imigrantes no Brasil.",
	"A importância da transparência na política para o fortalecimento da democracia.",
	"A política de combate ao terrorismo e suas implicações.",
	"Os ataques à políticas de direitos humanos e suas questões controversas.",
	"Os limites e possibilidades do ativismo político nas redes sociais.",
	"As diferenças entre regimes democráticos e autoritários.",
	"Os desafios da construção de uma democracia participativa.",
	"A importância da transparência na gestão pública.",
	"O papel da cooperação internacional na política global para solucionar situações de conflito de guerra.",
	"A viabilidade do socialismo na atualidade.",
	"A questão da distribuição de renda nos ideais socialistas.",
	"A visão do socialismo sobre propriedade privada e coletivização.",
	"A influência dos ideiais do socialismo na política internacional.",
	"Os desafios da implementação do socialismo na prática.",
	"As discussões sobre a aplicação do socialismo e a garantia dos direitos humanos.",
	"As divergências entre as correntes do socialismo.",
	"Discussões sobre sistemas econômicos alternativos ao capitalismo.",
	"O impacto das decisões do Estado na economia em sociedades socialistas.",
	"As discussões sobre igualdade de gênero no oriente médio.",
	"A história dos ideais socialistas no mundo e suas transformações ao longo do tempo.",
	"A crítica do socialismo ao liberalismo econômico.",
	"A influência dos ideais socialismo no pensamento político latino-americano.",
	"A formação da cultura numa sociedade com ideais socialistas.",
	"A questão do poder popular nos ideais socialistas.",
	"Os ideais socialistas e a liberdade de expressão.",
	"Os ideiais do socialismo e a crítica à globalização.",
	"A visão do socialismo sobre a propriedade intelectual.",
	"A Revolução Francesa: o impacto da igualdade e da liberdade na política e na sociedade.",
	"A Guerra Fria: como a disputa entre Estados Unidos e União Soviética moldou o mundo moderno.",
	"O Holocausto: como o genocídio afetou a humanidade e a luta contra o antissemitismo.",
	"A Revolução Industrial: como as mudanças tecnológicas transformaram a economia e a sociedade.",
	"A Primeira Guerra Mundial: suas consequências políticas e econômicas no mundo.",
	"A Segunda Guerra Mundial: como o conflito alterou o mapa geopolítico e as relações internacionais.",
	"A Idade Média: como as tradições dessa época ainda influenciam a cultura contemporânea.",
	"O Imperialismo: como as nações europeias se expandiram e colonizaram outros territórios.",
	"A Independência dos Estados Unidos: como a luta pela liberdade influenciou a luta por direitos civis no mundo.",
	"A Revolução Russa: como o socialismo e o comunismo se consolidaram na Rússia.",
	"A Conquista da América: o impacto da colonização na vida dos povos indígenas.",
	"A Revolução Industrial na Inglaterra: como as mudanças econômicas afetaram a vida da população.",
	"A Revolução Chinesa: como o país passou de uma monarquia para um estado socialista.",
	"A Queda do Muro de Berlim: como a unificação da Alemanha afetou a geopolítica mundial.",
	"A Revolução Cubana: como a luta pelo socialismo influenciou a América Latina.",
	"A Guerra do Vietnã: como o conflito afetou a geopolítica do sudeste asiático.",
	"A Revolução Mexicana: como o país se libertou do domínio colonial e se transformou em uma república democrática.",
	"A Revolução Industrial nos Estados Unidos: como a economia americana se tornou a mais poderosa do mundo.",
	"A Revolução Industrial na Alemanha: como a tecnologia alemã se tornou referência em todo o mundo.",
	"A Revolução Cultural Chinesa: como o país se transformou em uma ditadura comunista.",
	"A Guerra do Golfo: como o conflito afetou as relações internacionais e a geopolítica do Oriente Médio.",
	"A Guerra Fria na América Latina: como a influência dos Estados Unidos e da União Soviética afetou a região.",
	"A Primavera Árabe: como a luta por direitos civis e políticos afetou o Oriente Médio e o Norte da África.",
	"A Revolução Industrial no Japão: como a economia japonesa se tornou uma das mais importantes do mundo.",
	"A influência do pensamento iluminista na Revolução Francesa.",
	"A ascensão do nazismo na Alemanha e suas consequências na Segunda Guerra Mundial.",
	"A Guerra Fria: o conflito ideológico e a corrida armamentista entre EUA e URSS.",
	"O colonialismo europeu e seus impactos na África e Ásia.",
	"A crise de 1929 e a Grande Depressão: causas, consequências e respostas políticas.",
	"A Revolução Chinesa e a ascensão do Partido Comunista no país.",
	"A independência das colônias americanas e a formação dos Estados Unidos.",
	"O apartheid na África do Sul e a luta contra o racismo no mundo.",
	"O feminismo e sufragismo.",
	"A Revolução Cubana e as tensões entre Cuba e EUA.",
	"A queda do Muro de Berlim e o fim da Guerra Fria.",
	"O surgimento e evolução do movimento trabalhista no mundo.",
	"A Reforma Protestante e suas consequências na Europa e no mundo.",
	"O renascimento cultural e artístico na Europa dos séculos XV e XVI.",
	"A Revolução Russa e a ascensão do Partido Comunista no país.",
	"O movimento de descolonização na África e na Ásia.",
	"A Conferência de Yalta e o início da Guerra Fria.",
	"O processo de globalização financeira e suas consequências para os países em desenvolvimento.",
	"O surgimento e evolução do movimento ambientalista no mundo e as promessas para o futuro.",
	"O papel da Declaração de Independência na história dos Estados Unidos.",
	"As lutas pelos direitos civis nos Estados Unidos.",
	"A Guerra Fria e sua influência na história dos Estados Unidos.",
	"A Revolução Industrial e sua importância na história dos Estados Unidos.",
	"A imigração e sua relação com a história dos Estados Unidos.",
	"A Guerra do Vietnã e seus efeitos na história dos Estados Unidos.",
	"A história do movimento dos direitos das mulheres nos Estados Unidos até os dias atuais.",
	"A colonização dos Estados Unidos e sua relação com a história mundial.",
	"A Guerra Civil e sua influência na história dos Estados Unidos.",
	"A perspectiva dos direitos dos povos nativos indígenas nos Estados Unidos.",
	"A Segunda Guerra Mundial e sua influência na história dos Estados Unidos.",
	"A história do movimento pelos direitos dos trabalhadores nos Estados Unidos.",
	"O panorama das políticas externas dos Estados Unidos.",
	"A história do movimento pelos direitos dos negros nos Estados Unidos.",
	"A problemática do sistema de saúde dos Estados Unidos.",
	"A história da escravidão nos Estados Unidos.",
	"A violência no sistema educacional dos Estados Unidos.",
	"O direito ao porte de armas como uma garantia constitucional: reflexões sobre a constituição nos EUA.",
	"A necessidade da preservação da cultura africana para o mundo.",
	"A conexão entre o impacto da colonização e a situação econômica atual de países africanos.",
	"A influência da religião na vida política e social de países africanos.",
	"Como o turismo influencia a economia e cultura da África?",
	"Os efeitos da urbanização acelerada nas cidades africanas.",
	"A situação dos direitos humanos em países africanos e possíveis soluções para essa questão.",
	"As mulheres e a questão de gênero na sociedade e política africanas.",
	"A percepção internacional da África e o papel da mídia internacional nessa percepção.",
	"O desenvolvimento e redução da pobreza na África através do fomento da educação universal.",
	"A questão da escravidão moderna na África e suas consequências.",
	"Os desafios da construção de democracias estáveis em países africanos.",
	"As organizações internacionais na ajuda humanitária e desenvolvimento na África e as ramificações desse processo.",
	"O papel dos recursos naturais na política e economia de países africanos.",
	"A relação entre a guerra e a pobreza na África.",
	"A preservação da fauna e flora africanas e suas implicações econômicas.",
	"O combate à corrupção na política e economia africanas.",
	"A situação da saúde pública em países africanos e possíveis soluções para essa questão.",
	"As tradições africanas na formação da identidade nacional e sua influência no mundo moderno.",
	"A importância da literatura africana para a cultura mundial.",
	"A implementação de políticas de inclusão social em países africanos.",
	"A religião na política do Oriente Médio.",
	"A crise dos refugiados sírios e seu impacto no Oriente Médio e no mundo.",
	"A relação do petróleo com a economia do Oriente Médio e seu impacto global.",
	"Os conflitos étnicos e religiosos no Iraque e suas consequências.",
	"Discussões sobre a história da colonização no Oriente Médio.",
	"A situação dos direitos humanos no Irã e sua influência na política mundial.",
	"As perspectivas para a resolução do conflito na relação entre Israel e Palestina.",
	"A influência das redes sociais no ativismo político no Oriente Médio.",
	"A questão da igualdade de gênero no Oriente Médio e sua influência na política e na sociedade.",
	"Reflexões sobre a revolução islâmica no Irã na política e na sociedade do Oriente Médio.",
	"As religiões não-islâmicas no Oriente Médio e os desafios da coexistência religiosa.",
	"Fundamentalismo islâmico na política e na sociedade do Oriente Médio.",
	"As perspectivas para a cooperação regional entre o Oriente Médio e a Ásia Central.",
	"O nacionalismo árabe na política do Oriente Médio.",
	"A questão da democracia no Oriente Médio e suas perspectivas.",
	"A influência das potências mundiais na política do Oriente Médio e suas consequências.",
	"A China na economia global e seus impactos políticos e sociais.",
	"A crise de Rohingya em Mianmar e as políticas de refugiados na Ásia.",
	"A questão dos direitos dos animais na Ásia e as políticas internacionais.",
	"A dinâmica demográfica das grandes metrópoles brasileiras e os desafios urbanos.",
	"A baixa taxa de fecundidade no Brasil e suas implicações para o futuro.",
	"A imigração venezuelana no Brasil e as políticas públicas de acolhimento.",
	"A dinâmica demográfica das áreas rurais do Brasil e seus desafios.",
	"O crescimento da população idosa no Brasil e as políticas públicas de cuidado e assistência.",
	"A influência da demografia na distribuição de renda no Brasil e na concentração de riqueza.",
	"A questão da baixa escolaridade da população brasileira e suas implicações para a demografia.",
	"A exploração de recursos naturais em planetas vizinhos: uma solução para a escassez de recursos na Terra?",
	"A importância da cooperação internacional na exploração do espaço.",
	"A militarização do espaço: uma ameaça à segurança global?",
	"As implicações éticas da colonização de Marte.",
	"Fronteiras espaciais e a questão da soberania: quem tem direito à exploração do espaço?",
	"O impacto da exploração espacial na economia global.",
	"O turismo espacial: oportunidade de negócios ou ameaça ao meio ambiente?",
	"Reflexões sobre a segurança no transporte de passageiros e cargas para o espaço.",
	"Poluição espacial: a necessidade de medidas de gestão ambiental.",
	"Regulamentação e fiscalização da exploração espacial: um desafio para a governança global.",
	"Como as tecnologias mudaram o modo de se fazer guerra?",
	"Guerras civis: quais são as suas causas e como podem ser evitadas?",
	"Guerras e refugiados: como a guerra afeta a vida dos refugiados?",
	"Guerra e direitos humanos: quais os efeitos das guerras sobre os direitos humanos?",
	"A guerra contra o terrorismo: o que significa, quais são os seus limites e como pode ser vencida?",
	"A guerra e a economia: como a guerra afeta a economia de um país?",
	"Diálogos sobre guerra e a diplomacia.",
	"Como e por que razões as diferenças religiosas têm levado a guerras?",
	"Uma reflexão sobre as armas e o terror nuclear.",
	"Panorama dos impactos psicológicos da guerra sobre os soldados e civis.",
	"A guerra e a memória coletiva: como as guerras são lembradas ao longo do tempo e como isso afeta a sociedade?",
	"Suicídio entre jovens: fatores de risco e prevenção.",
	"O impacto do isolamento social na saúde mental e no aumento dos casos de suicídio.",
	"Reflexões sobre a dependência química como fator de risco para o suicídio.",
	"O tabu em torno do suicídio: por que ainda é difícil falar sobre o assunto?",
	"Suicídio entre idosos: reflexões sobre o envelhecimento, solidão e qualidade de vida.",
	"Suicídio entre grupos LGBTQ+: fatores de risco, prevenção e acolhimento.",
	"O impacto do suicídio na família e na comunidade: desafios e oportunidades de apoio e prevenção.",
	"A abolição universal da pena de morte.",
	"A necessidade de leis mais rígidas para proteger animais de estimação contra maus-tratos e abandono.",
	"O uso de animais em testes científicos.",
	"O papel das ONGs na proteção de animais ameaçados de extinção.",
	"Animais em circos e zoológicos: entretenimento ou exploração?",
	"O desmatamento e a perda de habitat de animais silvestres.",
	"A criação de animais em larga escala e o impacto ambiental da produção de carne.",
	"O comércio ilegal de animais: uma ameaça à biodiversidade.",
	"A necessidade de políticas públicas para controle da população de animais domésticos e errantes nas cidades.",
	"O acesso à justiça como um direito civil fundamental: quais são os principais obstáculos e como superá-los?",
	"Direitos civis e a garantia da liberdade religiosa no Brasil.",
	"A importância da educação para a promoção dos direitos civis e para a formação de uma sociedade mais justa e igualitária.",
	"Direitos civis e a luta contra a violência de gênero: como promover uma cultura de respeito e tolerância?",
	"A importância da imprensa livre e do acesso à informação para a promoção dos direitos civis e a garantia da democracia.",
	"O papel do Nordeste no desenvolvimento do Brasil: avanços e desafios.",
	"A Amazônia brasileira e a sua preservação: como garantir o desenvolvimento sustentável da região?",
	"A violência urbana nas grandes cidades brasileiras: o que pode ser feito para reduzir os índices de criminalidade?",
	"A ocupação desordenada do espaço urbano e seus impactos socioeconômicos e ambientais.",
	"A influência das culturas regionais na construção da identidade brasileira.",
	"Os desafios da educação no interior do Brasil: como garantir a igualdade de oportunidades para todos os estudantes?",
	"A preservação das culturas indígenas brasileiras: como valorizar e proteger a diversidade cultural do país?",
	"O impacto do turismo na economia e na cultura das regiões brasileiras.",
	"As contradições da região Sudeste: a riqueza econômica e as desigualdades sociais.",
	"A arte como forma de protesto e resistência política.",
	"O mercado de arte contemporânea e sua relação com a globalização e as desigualdades sociais.",
	"A arte como ferramenta para o combate à violência doméstica e de gênero."
	];
	
	const temaAleat = temas[Math.floor(Math.random() * temas.length)];
	quoteText.innerText = temaAleat;
}

speechBtn.addEventListener("click", ()=>{
    if(!quoteBtn.classList.contains("loading")){
        let utterance = new SpeechSynthesisUtterance(`tema sugerido: ${quoteText.innerText}. ATENÇÃO! ${authorName.innerText}`);
        synth.speak(utterance);
        setInterval(()=>{
            !synth.speaking ? speechBtn.classList.remove("active") : speechBtn.classList.add("active");
        }, 10);
    }
});

copyBtn.addEventListener("click", ()=>{
    navigator.clipboard.writeText(quoteText.innerText);
});

twitterBtn.addEventListener("click", ()=>{
	let auxTxt = 'ESCREVA UMA REDAÇÃO COM O TEMA: ';
	let auxTxt1 = ' — 1000 Temas de Redação.';
    let tweetUrl = `https://twitter.com/intent/tweet?url=${auxTxt}${quoteText.innerText}${auxTxt1}`;
    window.open(tweetUrl, "_blank");
});

quoteBtn.addEventListener("click", randomQuote);